site_name: Liri Developers Documentation

pages:
  - Home: 'index.md'
  - About:
    - Philosophy: 'about/philosophy.md'
    - Project Management: 'about/project-management.md'
  - Packaging:
    - Overview: 'packaging/index.md'
    - Snap: 'packaging/snap.md'
  - Contributing:
    - Contributor Guide: 'contributing/contributor-guide/index.md'
    - Build from Sources: 'contributing/build-sources.md'
    - Upstream Issues: 'contributing/upstream-issues.md'
    - Coding Conventions:
      - Design Philosophy: 'contributing/coding-conventions/design-philosophy.md'
      - C++ Coding Conventions: 'contributing/coding-conventions/cpp-conventions.md'
      - C++ Coding Style: 'contributing/coding-conventions/cpp-style.md'
      - QML Coding Conventions: 'contributing/coding-conventions/qml-conventions.md'
  - Modules:
    - Overview: 'modules/index.md'
    - Text:
      - Overview: 'modules/text/index.md'
      - Syntax Highlighting: 'modules/text/syntax-highlighting.md'
    - Browser:
      - Overview: 'modules/browser/index.md'
      - Shortcuts: 'modules/browser/shortcuts.md'
