site_name: Liri Developers Documentation

pages:
  - Home: 'index.md'
  - About:
    - Projects: 'about/projects.md'
  - Contributor Guide: 'contributor-guide/index.md'
  - Packaging:
    - Overview: 'packaging/index.md'
    - Snap: 'packaging/snap.md'
