name: Publish via GitHub Pages

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - rebuild

jobs:
  build:
    name: Deploy pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: docs.liri.io
